### ISSUE TITLE
Missing path

### ISSUE THREAD

**Issue by 01010011-01001110** [sohamjaiswal10/guilded-music-bot#1]
The path '/venv/Scripts' is missing.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/83935716/189171912-7145d28f-c944-45fc-a43d-8a863594b357.png">

**Comment by sohamjaiswal** [comment]
Sorry, this project won't work now as the client api is now unsupported. I would wait for the official bot api to get voice support, only then will we be able to get mainstream music bots. If you still want to try using the project, I would say you can setup a venv yourself and move the repo files into it and everything would work the same.
